algoritmo "CalcIdade"
// Função : idade dela
// Autor : CahLins
// Data : 20/06/2018
// Seção de Declarações 
var

ano_atual, ano_nasc, idade: Inteiro

inicio
// Seção de Comandos 

Escreva("Em que ano nos estamos? :")
Leia (ano_atual)
Escreva("Em que ano eu nasci? :")
Leia (ano_nasc)
idade <- ano_atual-ano_nasc
Escreval  ("Minha idade e: ", idade)

se (idade>= 21) entao
Escreval ("voce ja e de maior idade")
FimSe

fimalgoritmo
