algoritmo "Creuza02"
// Função :  converter reais em dolars e euros
// Autor : CahLins
// Data : 20/06/2018
// Seção de Declarações 
var

reais, dolares, euros: Real

inicio
// Seção de Comandos 

Escreval("Quantos reais eu tenho? :")
Leia (reais)
dolares <- reais/3.75
Escreval("Em dolares eu tenho :", dolares)
euros <- reais/4.34
Escreva("Em euros eu tenho :", euros)


fimalgoritmo
