algoritmo "somador3"
// Função :   repeticao de algoritimo
// Autor :  cah lins
// Data : 13/08/2018
// Seção de Declarações 
var
 n, s: inteiro
  resp: caractere
inicio
 s<- 0

        Repita
                 Escreva("Digite o valor ==> ")
                 Leia(n)
                 S<- s+n
                 Escreva("Voce quer continuar? [S/N] ")
                 Leia(resp)
        Ate (resp = "n")
        Escreval(" A soma de todos os valores digitados e ", s)

fimalgoritmo
